input()
print("why is andrew the worse on the team?")
input()
print ("because he works at summit")
input ()
print ("why is andrew such a plegde?")
input ()
print ("because he is super ferda")
input ()
print ("why does naoli always eat creps?")
input ()
print ("because hes dropy tia")
input ()
print ("why does naoli eat mcdonadls everyday")
input ()
print ("because hes dropy tia")
input ()
print ("rouse")
input ()
print ("and valle")
input ()
print ("all combined")
input ()
print ("why is giedon so cash money at lax")
input ()
print ("cause hes him")