print ("Hellooooooooooooooooooooo!")
print ("")
name = input ("What is your name? ")
print ("")
print (f"Hello {name} and welcome to CTE TUCKET UNIVERSITY")
print ("")
print ("We should get things started!")
print ("Lets make a story!")
print ("")
print ("")
person = input ("Pick an celebirty: ")
location = input ("Now pick a location: ")
food = input ("pick a food: ")
drink = input ("pick a drink: ")
clothes = input ("pick a clothing brand: ")
print ("")
print (f"One day a {person} was dripped out in {clothes} and they had a huge feast of {food} and {drink} in the heart of {location}")

 